### ISSUE TITLE
SDK with support for python 3

### ISSUE THREAD

**Issue by VathsalaAchar** [EXASOL/python-exasol#3]
I was wondering if there is already support for python 3.

I have worked on making the changes necessary to support an older version of the SDK on python 3 and was considering sharing my version but if there is no support I could create a python3 branch and contribute the changes?

**Comment by andrehacker** [comment]
Dear VathsalaAchar,
yes, we don't have any support yet for Python 3, so it would be great if you would be willing to contribute a pull request for python 3 support.
Ideally the new version supports both Python 2 and 3 so that we have to maintain only a single version - but not sure how this works out for this module, what do you think about this?

**Comment by andrehacker** [comment]
@VathsalaAchar,
just for clarification: Even if it would be a separate branch, it would still be interesting to have Python 3 support. At this point having a single codebase it is nice-to-have. If we have separate versions for python 2 and 3 we could still merge them in future.

**Comment by VathsalaAchar** [comment]
Hi @andrehacker .
Sorry for getting back to you so late, I've been away for a few weeks. 

Yes I'll work on a separate branch first and then we can see if it would be feasible to have a single version.

**Comment by expobrain** [comment]
Hi,

I did a similar job as @VathsalaAchar but my PR #6  supports both Python 2 and 3.

**Comment by andrehacker** [comment]
Hi @expobrain and @VathsalaAchar,
thanks a lot for your pull requests, and sorry @VathsalaAchar for the delay. We will review the pull requests the next days asap. BTW: I almost finished a new travis config which will enable you to test your forks and pull requests (currently both will always fail).
Best

**Comment by Volodymyrk** [comment]
Is Python3 supported now?

**Comment by wildraid** [comment]
JFYI, python 3.6+ is supported in pyexasol: https://github.com/badoo/pyexasol

**Comment by andrehacker** [comment]
Python 3 is now supported after merging #10 (@Ashafix) based on #6 (@expobrain).
