### ISSUE TITLE
Different behavior executing writeData() with two different machines

### ISSUE THREAD

**Issue by juliaberezkina** [exasol/python-exasol#9]
Hi,

I use writeData() to write dataframe's data into Exasol table , configurations on both machines are the same.
1. On the first machine the function successfully write data to table
2. On the second machine the function fail to write data to table , while **no** exception occurs
Everything is OK with the connection to db itself , i think that something is wrong with the write-to-file then import to db mechanism

Any help with understanding this mechanism, and debugging the problem would be helpfull

Thanks

**Comment by wildraid** [comment]
@juliaberezkina if you can run your script on Python 3.6+, you may try do this with pyexasol: https://github.com/badoo/pyexasol/

Syntax is slightly different. Here is the manual page for HTTP transport: https://github.com/badoo/pyexasol/blob/master/docs/HTTP_TRANSPORT.md

You need `import_from_pandas` or `import_from_callback` function.

I guess, there IS an exception in "python-exasol" package, but it happens in parallel thread and is not properly caught.
